// <auto-generated />
using System;
using FBIApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FBIApplication.Migrations
{
    [DbContext(typeof(FBIApplicationContext))]
    partial class FBIApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FBIApplication.Models.ParticipationModel", b =>
                {
                    b.Property<int>("ParticipationModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ParticipationModelId");

                    b.ToTable("ParticipationModel");
                });

            modelBuilder.Entity("FBIApplication.Models.PoliceModel", b =>
                {
                    b.Property<int>("PoliceModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("data_year")
                        .HasColumnType("int");

                    b.Property<int>("officer_count")
                        .HasColumnType("int");

                    b.Property<float>("officer_rate_per_1000")
                        .HasColumnType("real");

                    b.Property<int>("population")
                        .HasColumnType("int");

                    b.HasKey("PoliceModelID");

                    b.ToTable("PoliceModel");
                });

            modelBuilder.Entity("FBIApplication.Models.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ParticipationModelId")
                        .HasColumnType("int");

                    b.Property<int>("active_agency_count")
                        .HasColumnType("int");

                    b.Property<int>("agency_count_asr_submitting")
                        .HasColumnType("int");

                    b.Property<int>("agency_count_hc_submitting")
                        .HasColumnType("int");

                    b.Property<int>("agency_count_leoka_submitting")
                        .HasColumnType("int");

                    b.Property<int>("agency_count_nibrs_submitting")
                        .HasColumnType("int");

                    b.Property<int>("agency_count_pe_submitting")
                        .HasColumnType("int");

                    b.Property<int>("agency_count_srs_submitting")
                        .HasColumnType("int");

                    b.Property<int>("agency_count_supp_submitting")
                        .HasColumnType("int");

                    b.Property<int>("covered_agency_count")
                        .HasColumnType("int");

                    b.Property<string>("csv_header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("data_year")
                        .HasColumnType("int");

                    b.Property<int>("nibrs_population_covered")
                        .HasColumnType("int");

                    b.Property<double>("nibrs_population_percentage_covered")
                        .HasColumnType("float");

                    b.Property<int>("population")
                        .HasColumnType("int");

                    b.Property<int>("population_covered")
                        .HasColumnType("int");

                    b.Property<int>("published_agency_count")
                        .HasColumnType("int");

                    b.Property<int>("total_agency_count")
                        .HasColumnType("int");

                    b.Property<int>("total_population")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("ParticipationModelId");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("FBIApplication.Models.Result", b =>
                {
                    b.HasOne("FBIApplication.Models.ParticipationModel", null)
                        .WithMany("results")
                        .HasForeignKey("ParticipationModelId");
                });

            modelBuilder.Entity("FBIApplication.Models.ParticipationModel", b =>
                {
                    b.Navigation("results");
                });
#pragma warning restore 612, 618
        }
    }
}
